apiVersion: v1
kind: Service
metadata:
  name: cars-be
  labels:
    app: cars-be
spec:
  type: LoadBalancer
  selector:
    app: cars-be
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-be
  labels:
    app: cars-be
spec:
  selector:
    matchLabels:
      app: cars-be
  replicas: 1
  template:
    metadata:
      labels:
        app: cars-be
    spec:
      containers:
        - name: cars-be
          image: cars-be:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_db
            - name: POSTGRES_HOST
              value: cars-db
