apiVersion: v1
kind: Service
metadata:
  name: cars-db
  labels:
    name: cars-db
spec:
  type: ClusterIP
  selector:
    name: cars-db
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-db
  labels:
    name: cars-db
spec:
  selector:
    matchLabels:
      name: cars-db
  template:
    metadata:
      name: cars-db
      labels:
        name: cars-db
    spec:
      containers:
        - name: cars-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: cars-db
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cars-config
                  key: postgres_db
